<?php
/**
 * @file
 * Main module for the ExactTarget API.  This file implements the public and
 * internal "private" functions used to wrap the ExactTarget XML API.
 */

/*
 * Start of Drupal hook implementations
 */

/**
 * Implements hook_menu().
 */
function exact_target_api_menu() {
  $items = array();

  $items['admin/config/services/exact-target-api'] = array(
    'title' => 'ExactTarget API',
    'description' => 'Configure integration with Exact Target API',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('exact_target_api_configure_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'exact_target_api.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Start of "private" utility functions for this module
 */

/**
 * Helper function to retrieve config info
 */
function _exact_target_api_get_config() {
  return variable_get('exact_target_api_cfg');
}

/**
 * Helper function to store config info
 */
function _exact_target_api_set_config($cfg) {
  $old_cfg = variable_get('exact_target_api_cfg', array());
  // if the Client Secret wasn't set don't overwrite the one we have stored
  $cfg['et_api_client_secret'] = $cfg['et_api_client_secret'] ?: $old_cfg['et_api_client_secret'];

  if (is_array($cfg)) {
    variable_set('exact_target_api_cfg', $cfg);
  }
}

/**
 * Start of public API methods
 */

/**
 * Retrieves profile and preference attributes (Date Extensions) defined in the ET account
 *
 * @param $filter
 *  Array containing the filter properties
 * @return $ET_Get object containing results and status messages.
 *
 * @see https://developer.salesforce.com/docs/atlas.en-us.mc-sdks.meta/mc-sdks/data-extension-column-retrieve.htm
 */
function exact_target_api_get_attributes($filter = array()) {
  $client = exact_target_api_get_client();
  if (!$client) {
    return FALSE;
  }
  try {
    $dataextensioncolumn = new ET_DataExtension_Column();
    $dataextensioncolumn->authStub = $client;
    if (!empty($filter)) {
      $dataextensioncolumn->filter = $filter;
    }
    $response = $dataextensioncolumn->get();
  }
  catch (Exception $e) {
    exact_target_api_log($e);
  }

  return $response;
}

/**
 * log exceptions
 */
function exact_target_api_log($e) {
  $errors = variable_get('error_level', 0);
  if (user_access('administer site configuration') && $errors) {
    drupal_set_message(t('Exception Occurred: %message', array('%message' => $e->getMessage())), 'error');
  }
  watchdog('exact_target_api', 'Exception Occurred: %message<br/><pre>@e</pre>', array('%message' => $e->getMessage(), '@e' => print_r($e, TRUE)), WATCHDOG_ERROR);
}

/**
 * Retrieves all lists for this account
 * @see https://developer.salesforce.com/docs/atlas.en-us.mc-sdks.meta/mc-sdks/list-retrieve.htm
 *
 * @param $props
 *  An array of properties to return, if empty all properties will be returned
 * @param $filter
 *  A filter to limit the number of lists to be returned. @see https://developer.salesforce.com/docs/atlas.en-us.mc-sdks.meta/mc-sdks/list-retrieve.htm#filter-get-requests
 * @param $array_key
 *  A String representing a property of the list object. This is the key the
 *  array is keyed with. Caution, usage of some keys will cause data loss if
 *  more than one list share that key. defaults to "ID" which is the numeric
 *  unique ID of the list.
 * @return
 *  An array of list objects keyed by $array_key
 */
function exact_target_api_get_lists($props = array(), $filter = array(), $array_key = 'ID') {
  $client = exact_target_api_get_client();
  if (!$client) {
    return FALSE;
  }
  try {
    $list = new ET_List();
    $list->authStub = $client;

    if (!empty($props)) {
      $list->props = $props;
    }

    if (!empty($filter)) {
      $list->filter = $filter;
    }
    $response = $list->get();
  }
  catch (Exception $e) {
    exact_target_api_log($e);
  }


  $old_lists = $response->results;
  $lists = array();
  foreach ($old_lists AS $this_list) {
    $lists[$this_list->{$array_key}] = $this_list;
  }

  return $lists;
}

/**
 * retrieve the location of the cached WSDL, and cache it if needs to be cached
 * or refreshed
 */
function exact_target_api_fetch_wsdl($cfg) {
  $wsdl_uri = file_build_uri('exact_target_api.wsdl');
  if ($wrapper = file_stream_wrapper_get_instance_by_uri($wsdl_uri)) {
    $realpath = $wrapper->realpath();
    $redownload = FALSE;
    if (!file_exists($realpath)) {
      $redownload = TRUE;
    }
    $ttl = $cfg['exact_target_api_wsdl_cache_ttl'] ?: 604800;
    if (filemtime($realpath) + $ttl <= REQUEST_TIME) {
      $redownload = TRUE;
    }
  }

  $wsdl_url = 'https://webservice.' . $cfg['et_cfg_endpoint'] . '.exacttarget.com/etframework.wsdl';
  if ($redownload) {
    $response = drupal_http_request($wsdl_url);
    if (floor($response->code/100)*100 == 200) {
      file_put_contents($wsdl_uri, $response->data);
    }
    else {
      watchdog('exact_target_api', 'Could not cache Exact Target WSDL: @code @status_message<br/><pre>@response</pre>', array('@code' => $response->code, '@status_message' => $response->status_message, '@response' => print_r($response, TRUE)), WATCHDOG_ERROR);
    }
  }
  else if (isset($realpath) && !empty($realpath)) {
    return $realpath;
  }
  else {
    return FALSE;
  }



}
/**
 * get an instance of the ET_Client with the current settings
 *
 * @return
 *  An ET_Client object with authentication tokens already set.
 */
function exact_target_api_get_client() {
  // WSDL and endpoint links are here https://developer.salesforce.com/docs/atlas.en-us.mc-apis.meta/mc-apis/getting_started_developers_and_the_exacttarget_api.htm
  $cfg = _exact_target_api_get_config();//return FALSE;

  $params = array(
    //'defaultwsdl' => $cfg[''],
    'clientid' => $cfg['et_api_client_id'],
    'clientsecret' => $cfg['et_api_client_secret'],
    //'appsignature' => $cfg[''],
    'xmlloc'  => exact_target_api_fetch_wsdl($cfg),
    'defaultwsdl' => 'https://webservice.' . $cfg['et_cfg_endpoint'] . '.exacttarget.com/etframework.wsdl',
  );

  if (module_exists('chr')) {
    // load possible proxy settings that the cURL HTTP Request module
    // ( https://www.drupal.org/project/chr ) uses in case it is how the system in
    // configured
    $chr_proxy_settings = variable_get('http_proxy', array());
    if (!empty($proxy_settings)) {
      if (!empty($chr_proxy_settings['server'])) {
        $params['proxyhost'] = $chr_proxy_settings['server'];
      }
      if (!empty($chr_proxy_settings['port'])) {
        $params['proxyport'] = $chr_proxy_settings['port'];
      }
      if (!empty($chr_proxy_settings['username'])) {
        $params['proxyusername'] = $chr_proxy_settings['username'];
      }
      if (!empty($chr_proxy_settings['password'])) {
        $params['proxypassword'] = $chr_proxy_settings['password'];
      }
    }
  }
  else {
    // check is there are standard Drupal 7 proxy settings
    if ($proxy_server = variable_get('proxy_server', FALSE)) {
      $params['proxyhost'] = $proxy_server;
    }
    if ($proxy_port = variable_get('proxy_port', FALSE)) {
      $params['proxyport'] = $proxy_port;
    }
    if ($proxy_username = variable_get('proxy_username', FALSE)) {
      $params['proxyusername'] = $proxy_username;
    }
    if ($proxy_password = variable_get('proxy_password', FALSE)) {
      $params['proxypassword'] = $proxy_password;
    }
  }
  $library = libraries_load('FuelSDK-PHP');
  try {
    $myclient = new ET_Client(FALSE, FALSE, $params);
  }
  catch (Exception $e) {
    exact_target_api_log($e);
    return FALSE;
  }
  return $myclient;
}

/**
 * Retrieves list information for a given ID. If the items in in the db cache
 * (unexpired) it is retrieved from there, else it is retrieved from the remote
 * server, cached in the database, and returned
 *
 * @param $list
 *  This is the numeric ID of the list or the list object. If the list object is
 *  passed the object is cached in the database and the database timestamp for
 *  that object is updated. If the ID is passed the database is queried and if
 *  the list isn't cached or is expired it is fetched from the remote
 * @return
 *  the list object
 * @see exact_target_api_get_lists
 */
function exact_target_api_get_list_info($list) {
  $cfg = _exact_target_api_get_config();

  if (is_object($list)) {
    $listid = $list->ID;
  }
  else {
    $listid = $list;
  }
  static $cache = array();
  $listinfo = array();

  // Pre-pop our lookup cache for this page load from the DB
  if (empty($cache)) {
    $result = db_select('et_list_cache', 'et')
    ->fields('et')
    ->condition('update_timestamp', REQUEST_TIME - ($cfg['exact_target_list_cache_ttl'] ?: 86400),'>')
    ->execute()
    ->fetchAllAssoc('listid');

    if ($result) {
      foreach ($result as $record) {
        $cache[$record->listid] = unserialize($record->list_object);
      }
    }
  }

  // Now, let's see if we have a cached copy of the list info:
  if (!empty($cache[$listid])) {
    $listinfo = $cache[$listid];
  }

  // If not, retrieve the info and cache it in the DB
  else {
    if (!is_object($list)) {
      // the item passed in is not an object let's request this object from the
      // remote server to use and cache
      $filter = array(
        'Property' => 'ID',
        'SimpleOperator' => 'equals',
        'Value' => $listid
      );
      $requested_result = exact_target_api_get_lists(array(), $filter);
      if (!empty($requested_result[$listid])) {
        $list = $listinfo = $requested_result[$listid];
      }
    }

    if (is_object($list)) {
      if (!empty($list)) {

        // Store in DB:
         $query = db_merge('et_list_cache')
          ->key(array('listid' => $list->ID))
          ->fields(array(
            'list_name' => $list->ListName,
            'list_type' => $list->Type,
            'list_object' => serialize($list),
            'update_timestamp' => REQUEST_TIME,
          ))
          ->execute();

        // Store in static cache
        $cache[$listid] = $listinfo;
      }
    }
  }

  return $listinfo;
}

/**
 * Creates a new subscriber list
 *
 * The List Add call creates a new subscriber list. The call requires the
 * list name and type as input, and you receive the listID of the new list
 * as a result of the call. Once the list has been created, you can add
 * subscribers.
 *
 * @param $name
 *  String containing a title for the list
 * @param $description
 *  String containing the description of the list
 * @param $type
 *  String containing either 'Public' or 'Private'
 * @return
 *  ET_Post object containing status information including IDs for the newly
 *  created list
 *
 * @see https://developer.salesforce.com/docs/atlas.en-us.mc-sdks.meta/mc-sdks/list-create.htm
 */
function exact_target_api_add_list($name, $description = 'SDK Created List', $type = 'Public') {
  $client = exact_target_api_get_client();
  if (!$client) {
    return FALSE;
  }
  try {
    $list = new ET_List();
    $list->authStub = $client;
    $list->props = array('ListName' => $name, 'Description' => $description, 'Type' => $type);
    $results = $list->post();
  }
  catch (Exception $e) {
    exact_target_api_log($e);
  }

  return $results;
}

/**
 * Deletes a list and all subscribers who belong to that list
 *
 * @param
 *  String containing the Id of the list to delete
 * @return
 *  ET_Delete object containing results of delete action
 *
 * @see https://developer.salesforce.com/docs/atlas.en-us.mc-sdks.meta/mc-sdks/list-delete.htm
 */
function exact_target_api_delete_list($listid) {
  $client = exact_target_api_get_client();
  if (!$client) {
    return FALSE;
  }
  try {
    $list = new ET_List();
    $list->authStub = $client;
    $list->props = array('ID' => $listid);
    $results = $list->delete();
  }
  catch (Exception $e) {
    exact_target_api_log($e);
  }

  return $results;
}

/**
 * Renames a subscriber list
 *
 * @param $listid
 *  String containing the ID of the list
 * @param $name
 *  String containing the new name for the list
 * @return
 *  ET_Patch objectcontaining results of update action
 *
 * @see https://developer.salesforce.com/docs/atlas.en-us.mc-sdks.meta/mc-sdks/list-update.htm
 */
function exact_target_api_rename_list($listid, $name) {
  $client = exact_target_api_get_client();
  if (!$client) {
    return FALSE;
  }
  try {
    $list = new ET_List();
    $list->authStub = $client;
    $list->props = array('ID' => $listid, 'ListName'=> $name);
    $results = $list->patch();
  }
  catch (Exception $e) {
    exact_target_api_log($e);
  }

  return $results;
}

/**
 * Retrieves the profile and preference attributes for all subscribers on a
 * specified list
 *
 * @param $listid
 *  String containing the ID of the list, if blank subscribers for all lists
 *  will be returned
 * @param $status
 *  String representing the requested Status filter, either 'Active' or
 *  'Unsubscribed'. As the SDK only allows for filtering on one Property at a
 *  time the ListID takes precedence.
 * @return
 *  Array of objects representing list subscribers
 *
 * @see https://developer.salesforce.com/docs/atlas.en-us.mc-sdks.meta/mc-sdks/list-subscriber-retrieve.htm
 */
function exact_target_api_get_list_subscribers($listid = '', $status = '') {
  $client = exact_target_api_get_client();
  if (!$client) {
    return FALSE;
  }
  try {
    $listsubscriber = new ET_List_Subscriber();
    $listsubscriber->authStub = $client;
    if (!empty($status)) {
      $listsubscriber->filter = array(
        'Property' => 'Status',
        'SimpleOperator' => 'equals',
        'Value' => $status,
      );
    }
    if (!empty($listid)) {
      $listsubscriber->filter = array(
        'Property' => 'ListID',
        'SimpleOperator' => 'equals',
        'Value' => $listid,
      );
    }
    $response = $listsubscriber->get();
  }
  catch (Exception $e) {
    exact_target_api_log($e);
  }

  return $response->results;
}

/**
 * Get organizations within the ExactTarget account.
 *
 * @param $props
 *  Array of properties to return
 * @param $filter
 *  Array containing filter directives for the search
 *
 * @return
 *  ET_Get object containing results of Organizations request.
 */
function exact_target_api_get_organizations($props = array(), $filter = array()) {
  $client = exact_target_api_get_client();
  if (!$client) {
    return FALSE;
  }
  try {
    $org = new ET_Organization();
    $org->authStub = $client;
    if (!empty($props)) {
      $org->props = $props;
    }
    if (!empty(filter)) {
      $org->filter = $filter;
    }
    $response = $org->get();
  }
  catch (Exception $e) {
    exact_target_api_log($e);
  }
  return $response;
}

/**
 * Get users with access to the ExactTarget account.
 *
 * @param $props
 *  Array of properties to return
 * @param $filter
 *  Array containing filter directives for the search
 *
 * @return
 *  ET_Get object containing results of Organizations request.
 */
function exact_target_api_get_users($props = array(), $filter = array()) {
  $client = exact_target_api_get_client();
  if (!$client) {
    return FALSE;
  }
  try {
    $user = new ET_User();
    $user->authStub = $client;
    if (!empty($props)) {
      $user->props = $props;
    }
    if (!empty(filter)) {
      $user->filter = $filter;
    }
    $response = $user->get();
  }
  catch (Exception $e) {
    exact_target_api_log($e);
  }
  return $response;
}

/**
 * Returns information about subscribers currently on the Master Unsubscribe list.
 * Technically there is not a Master Unsubscribe list any more, all subscribers
 * are added to a list called 'All Subscribers'. in addition to any other list
 * they may be on. If a subscriber's status is changes to 'Unsubscribe' on the
 * 'All Subscribers' list then they are automatically Unsubscribed from all
 * lists. If the subscriber is not Active on the 'All Subscribers' list then
 * they cannot be subscribed to any list, or made 'Active' on any list until
 * they are changed to Status='Active' in the 'All Subscribers' list.
 *
 * @see https://developer.salesforce.com/docs/atlas.en-us.mc-sdks.meta/mc-sdks/list-subscriber-retrieve.htm
 */
function exact_target_api_get_master_unsubscribe_list() {
  // The Master list is called 'All Subscribers'
  $query = db_select('et_list_cache', 'et');
  $query->addField('et', 'listid');
  $query->condition('list_name', 'All Subscribers');
  $result = $query->execute();
  $master_list_id = $result->fetchField();

  $client = exact_target_api_get_client();
  if (!$client) {
    return FALSE;
  }
  try {
    $listsubscriber = new ET_List_Subscriber();
    $listsubscriber->authStub = $client;
    // the SDK doesn't allow for multiple filters to be applied, just one
    $listsubscriber->filter = array(
      'Property' => 'Status',
      'SimpleOperator' => 'equals',
      'Value' => 'Unsubscribed',
    );
    $response = $listsubscriber->get();
    foreach ($response->results AS $key => $subscriber) {
      if ($subscriber->ListID != $master_list_id) {
        // strip out all the subscribers not in the master list
        unset($response->results[$key]);
      }
    }
    $response->results = array_values($response->results);
  }
  catch (Exception $e) {
    exact_target_api_log($e);
  }
  return $response;
}

/**
 * Adds a subscriber to a list
 *
 * @param $listid
 *  the ID of the list
 * @param $email
 *  String containing the e-mail address to send e-mails to.
 * @return
 *  ET_Post object with request status information including errors
 * 
 * @see https://developer.salesforce.com/docs/atlas.en-us.mc-sdks.meta/mc-sdks/add-subscriber-to-list.htm
 */
function exact_target_api_add_subscriber($listid, $email) {
  if (!is_array($listid)) {
    $list_id = array($listid);
  }

  $client = exact_target_api_get_client();
  if (!$client) {
    return FALSE;
  }
  try {
    $response = $client->AddSubscriberToList($email, $listid, $email);
  }
  catch (Exception $e) {
    exact_target_api_log($e);
  }
  return $response;
}

/**
 * Removes a subscriber from a single list, the user will not be completely
 * deleted and they will remain on the list, but their status will be changed to
 * 'Unsubscribed'.
 *
 * @param $listid
 *  String with the Id of the list
 * @param $email
 *  String with the email address to be removed from the list
 * @param $subkey
 *  String with the SubscriberKey for the user, If this is not provided the
 *  $email will be used to lookup the subscriber and get the SubscriberKey
 * @return
 *  ET_Patch object with results information.
 *
 * @see https://developer.salesforce.com/docs/atlas.en-us.mc-sdks.meta/mc-sdks/subscriber-update.htm
 */
function exact_target_api_remove_subscriber($listid, $email, $subkey = NULL) {
  $client = exact_target_api_get_client();
  if (!$client) {
    return FALSE;
  }
  if (empty($subkey)) {
    // fetch the subscriber because we don't have the subkey
    $sub = exact_target_api_get_subscriber_by_email($email);
    $subkey = $sub->SubscriberKey;
  }


  $lists = array(
    'ID' => $listid,
    'Status' => 'Unsubscribed',
  );
  try {
    $subscriber = new ET_Subscriber();
    $subscriber->authStub = $client;
    $subscriber->props = array(
      'SubscriberKey' => $subkey,
      'Lists' => $lists,
    );
    $results = $subscriber->patch();
  }
  catch (Exception $e) {
    exact_target_api_log($e);
  }

  return $results;
}

/**
 * Unsubscribe a user from all lists. The user still appears on the list but the
 * status is set to 'Unsubscribed'. This includes the "All Subscribers" list;
 * with the user on the "All Subscribers" list set to "Unsubscribed" the user
 * cannot be subscribed to any list until they are changed to "Active" on the
 * "All Subscribers" list.
 *
 * @param $email
 *  String of the email address to unsubscribe.
 * @return
 *  ET_Patch object with results information.
 */
function exact_target_api_unsubscribe_all($email) {
  $client = exact_target_api_get_client();
  if (!$client) {
    return FALSE;
  }
  $sub = exact_target_api_get_subscriber_by_email($email);
  try {
    $subscriber = new ET_Subscriber();
    $subscriber->authStub = $client;
    $subscriber->props = array(
      'SubscriberKey' => $sub->SubscriberKey,
      'Status' => 'Unsubscribed',
    );
    $results = $subscriber->patch();
  }
  catch (Exception $e) {
    exact_target_api_log($e);
  }

  return $results;
}

/**
 * Deletes a subscriber entirely from your account.
 *
 *
 * @param $subscriber_key
 *  String containing the SubscriberKey returned in lists of subscribers. By
 *   default subscribers created by this module use the email address as the
 *   SubscriberKey
 * @return
 *  ET_Delete object containing errors and status codes
 *
 * @see https://developer.salesforce.com/docs/atlas.en-us.mc-sdks.meta/mc-sdks/subscriber-delete.htm
 */
function exact_target_api_delete_subscriber($subscriber_key) {
  $client = exact_target_api_get_client();
  if (!$client) {
    return FALSE;
  }
  try {
    $subscriber = new ET_Subscriber();
    $subscriber->authStub = $client;
    $subscriber->props = array('SubscriberKey' => $subscriber_key);
    $results = $subscriber->delete();
  }
  catch (Exception $e) {
    exact_target_api_log($e);
  }
  return $results;
}

/**
 * Updates attribute values and the status of an existing subscriber
 *
 * The Subscriber Edit (Update) call updates attribute values and the status
 * of an existing subscriber. This call can also be used to reactivate a
 * subscriber on the Master Unsubscribe list. You must provide the email
 * address and the listID or subscriberID if you are reactivating a
 * subscriber. The call returns a subscriberID for each subscriber successfully
 * updated.
 *
 * @param $email
 *  String representation of the user's email address
 * @param $props
 *  array of properties to set on the user account
 * @param $subkey
 *  String representation of the user's unique SubscriberKey. If this is left
 *  blank an extra API call will be made to look up the user's SubscriberKey
 *  using the email address provided
 * @return
 *  ET_Patch object with results information.
 *
 * @see https://developer.salesforce.com/docs/atlas.en-us.mc-sdks.meta/mc-sdks/subscriber-update.htm
 */
function exact_target_api_update_subscriber($email, $props = array(), $subkey = NULL) {
  $client = exact_target_api_get_client();
  if (!$client) {
    return FALSE;
  }
  if (empty($subkey)) {
    // fetch the subscriber because we don't have the subkey
    $sub = exact_target_api_get_subscriber_by_email($email);
    $subkey = $sub->SubscriberKey;
  }
  $default_props = array(
    'SubscriberKey' => $subkey,
  );
  try {
    $subscriber = new ET_Subscriber();
    $subscriber->authStub = $client;
    $subscriber->props = array_merge($default_props, $props);
    $results = $subscriber->patch();
  }
  catch (Exception $e) {
    exact_target_api_log($e);
  }
  return $results;
}

/**
 * Places one or more email addresses on your Master Unsubscribe list
 *
 * @see exact_target_api_unsubscribe_all().
 */
function exact_target_api_unsubscribe_master($email) {
  return exact_target_api_unsubscribe_all($email);
}

/**
 * Retrieves all profile and preference attribute values for a subscriber
 *
 * @param $id
 *  String of the key to search on, usually the e-mail address or subscriber key
 * @param $key
 *  String with name of property to search on for the ID, usually 'EmalAddress'
 *  or 'SubscriberKey'
 * @return
 *  Object with Subscriber information and a lists property containing an array
 *  of lists the user is (un)subscribed to
 *
 * @see https://developer.salesforce.com/docs/atlas.en-us.mc-sdks.meta/mc-sdks/subscriber-retrieve.htm
 * @see https://developer.salesforce.com/docs/atlas.en-us.mc-sdks.meta/mc-sdks/list-subscriber-retrieve.htm
 */
function exact_target_api_get_subscriber_by_id($id, $key = 'SubscriberKey') {
  $client = exact_target_api_get_client();
  if (!$client) {
    return FALSE;
  }
  try {
    $subscriber = new ET_Subscriber();
    $subscriber->authStub = $client;
    $subscriber->filter = array(
      'Property' => $key,
      'SimpleOperator' => 'equals',
      'Value' => $id,
    );
    $sub_response = $subscriber->get();
    $subscriber = $sub_response->results[0];
    $listsubscriber = new ET_List_Subscriber();
    $listsubscriber->authStub = $client;
    $listsubscriber->filter = array(
      'Property' => 'SubscriberKey',
      'SimpleOperator' => 'equals',
      'Value' => $subscriber->SubscriberKey,
    );
    $list_response = $listsubscriber->get();
  }
  catch (Exception $e) {
    exact_target_api_log($e);
  }

  $subscriber->lists = array();
  foreach ($list_response->results AS $this_list) {
    $subscriber->lists[] = $this_list;
  }
  return $subscriber;
}

/**
 * Retrieves all profile and preference attribute values for a subscriber by
 * email address.
 *
 * @param $email
 *  String with the email address
 * @return
 *  Object with Subscriber information and a lists property containing an array
 *  of lists the user is (un)subscribed to
 *
 * @see exact_target_api_get_subscriber_by_id().
 */
function exact_target_api_get_subscriber_by_email($email) {
  return exact_target_api_get_subscriber_by_id($email, 'EmailAddress');
}

/**
 * Implements hook_libraries_info().
 */
function exact_target_api_libraries_info() {

  $libraries['FuelSDK-PHP'] = array(
    'name' => 'FuelSDK-PHP',
    'vendor url' => 'https://github.com/salesforce-marketingcloud/FuelSDK-PHP',
    'download url' => 'https://github.com/salesforce-marketingcloud/FuelSDK-PHP/archive/v1.0.0.zip',
    'version arguments' => array(
      'file'    => 'README.md',
      'pattern' => '/.*Version\s([.0-9]*).*/',
    ),
    'files' => array(
      'php' => array(
        'src/ET_Client.php',
        'src/ET_Util.php',
        'src/ET_BaseObject.php',
        'src/ET_BaseObjectRest.php',
        'src/ET_GetSupportRest.php',
        'src/ET_CUDSupportRest.php',
        'src/ET_Asset.php',
        'src/ET_Constructor.php',
        'src/ET_Get.php',
        'src/ET_GetRest.php',
        'src/ET_GetSupport.php',
        'src/ET_BounceEvent.php',
        'src/ET_Campaign.php',
        'src/ET_Campaign_Asset.php',
        'src/ET_ClickEvent.php',
        'src/ET_Configure.php',
        'src/ET_CUDSupport.php',
        'src/ET_CUDWithUpsertSupport.php',
        'src/ET_ContentArea.php',
        'src/ET_Continue.php',
        'src/ET_DataExtension.php',
        'src/ET_DataExtensionColumn.php',
        'src/ET_DataExtensionRow.php',
        'src/ET_Delete.php',
        'src/ET_DeleteRest.php',
        'src/ET_Email.php',
        'src/ET_Email_SendDefinition.php',
        'src/ET_Folder.php',
        'src/ET_Import.php',
        'src/ET_Info.php',
        'src/ET_List.php',
        'src/ET_List_Subscriber.php',
        'src/ET_Message_Guide.php',
        'src/ET_OEM_Client.php',
        'src/ET_OpenEvent.php',
        'src/ET_Organization.php',
        'src/ET_Patch.php',
        'src/ET_PatchRest.php',
        'src/ET_Perform.php',
        'src/ET_Post.php',
        'src/ET_PostRest.php',
        'src/ET_ProfileAttribute.php',
        'src/ET_PutRest.php',
        'src/ET_Send.php',
        'src/ET_SendEvent.php',
        'src/ET_Subscriber.php',
        'src/ET_TriggeredSend.php',
        'src/ET_UnsubEvent.php',
        'src/ET_User.php',
        'src/ET_Util.php',
        //'vendor/robrichards/xmlseclibs/xmlseclibs.php',
      ),
    ),
  );

  return $libraries;
}
